defmodule RevoluchatWeb.Plugs.Session do
  @behaviour Plug
  
  def init(opts), do: opts
  
  def call(conn, _opts) do
    session_opts = RevoluchatWeb.Endpoint.session_options()
    session_plug_opts = Plug.Session.init(session_opts)
    Plug.Session.call(conn, session_plug_opts)
  end
end

defmodule RevoluchatWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :revoluchat

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options {RevoluchatWeb.Endpoint, :session_options, []}

  socket("/socket", RevoluchatWeb.UserSocket,
    websocket: [
      check_origin: {RevoluchatWeb.Endpoint, :check_origin?, []},
      timeout: 45_000,
      compress: true,
      # 1MB max frame size
      max_frame_size: 1_048_576
    ],
    longpoll: [connect_info: [session: @session_options]]
  )

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], check_origin: {RevoluchatWeb.Endpoint, :check_origin?, []}],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :revoluchat,
    gzip: not code_reloading?,
    only: RevoluchatWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :revoluchat)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(RevoluchatWeb.Plugs.Session)

  # Force HTTPS
  # plug Plug.SSL,
  #   rewrite_on: [:x_forwarded_proto],
  #   hsts: true,
  #   expires: 31_536_000

  plug(RevoluchatWeb.Router)

  def check_origin?(%Plug.Conn{} = conn) do
    case Plug.Conn.get_req_header(conn, "origin") do
      [origin] -> check_origin?(origin)
      _ -> true
    end
  end

  def check_origin?(origin) when is_binary(origin) do
    case System.get_env("CSP_CONNECT_SRC") do
      nil ->
        true
      csp ->
        clean_csp = String.replace(csp, ~r/['\"]/, "")
        allowed = String.split(clean_csp)
        
        origin_uri = URI.parse(origin)
        origin_host = origin_uri.host
        
        Enum.any?(allowed, fn item ->
          cond do
            item == "'self'" ->
              false
            String.starts_with?(item, "*.") ->
              suffix = String.slice(item, 2..-1//1)
              origin_host && String.ends_with?(origin_host, suffix)
            true ->
              item_host = item |> String.replace(~r|^https?://|, "") |> String.replace(~r|^wss?://|, "")
              origin_host == item_host
          end
        end)
    end
  end

  def check_origin?(_), do: true

  def session_options do
    signing_salt = System.fetch_env!("SESSION_SIGNING_SALT")
    [
      store: :cookie,
      key: "_site_key",
      signing_salt: signing_salt,
      same_site: "Lax",
      secure: true,
      http_only: true
    ]
  end
end


