defmodule RevoluchatWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :revoluchat

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_revoluchat_key",
    signing_salt: "aCjBnSTY",
    same_site: "Lax"
  ]

  socket "/socket", RevoluchatWeb.UserSocket,
    websocket: [
      timeout: 45_000,
      compress: true,
      # 1MB max frame size
      max_frame_size: 1_048_576
    ],
    longpoll: [connect_info: [session: @session_options]]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :revoluchat,
    gzip: not code_reloading?,
    only: RevoluchatWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :revoluchat
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Force HTTPS
  plug Plug.SSL,
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    expires: 31_536_000

  plug RevoluchatWeb.Router
end
